### ISSUE TITLE
代码中没看到论文中所说的迭代更新的过程啊

### ISSUE THREAD

**Issue by Gakiii** [Peter7Yao/RNM#1]
我看代码的model中只有对向量进行联合训练的过程，好像没看到论文中的迭代跟新的过程，如果有能否指出来一下

**Comment by Peter7Yao** [comment]
迭代更新的代码在Model.py 374-377行，调用的具体实现在Test.py 中

**Comment by Gakiii** [comment]
> 迭代更新的代码在Model.py 374-377行，调用的具体实现在Test.py 中

看到了，感谢！
